language: node_js
sudo: false
node_js:
  - 10
cache:
  directories:
    - '$HOME/.npm'
    - node_modules
before_script:
  - npm config set -g production false
  - npm install
script:
  - CODECOV_TOKEN=$CODECOV_TOKEN npm test
  - if [ "$TESTS_FAILED" -ne 0 ]; then exit 1; fi
  - CODECOV_TOKEN=$CODECOV_TOKEN npm run coverage
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ] && [ "$TRAVIS_BRANCH" = "master" ]; then
    npm config set git-tag-version=false && NPM_VERSION=$(npm version patch); fi
  - if [ "$TRAVIS_PULL_REQUEST" = "false" ] && [ "$TRAVIS_BRANCH" = "master" ]; then
    env COMMIT_MESSAGE=${NPM_VERSION:1} GITHUB_TOKEN=${GITHUB_TOKEN} ./bashes/push.sh;
    fi
after_failure:
  - dmesg | grep -i kill
  - sleep 4
deploy:
  provider: npm
  email: saikatchakrabortty2@gmail.com
  api_key:
    secure: CbgUOYFN+s2+4ixDSFn8ab0YPxrsCTA4yuHzBV0Nsjn9BqrsyOEjW3TdwWzvOAqdTIYPcjD6jJ1BDzgY4tqMZhZlJs7CqDkuc87ekj1equV/dG9wZ/PzXbIG91iklHGgybAWdpsBccYqv+IF0e28PKsIRxEUAjYV7CV9IuKDIuWoTFkJBsxHtF5p1H/XyevhqLj/dmuv1G+OXbTDRBzISydy+83S8S8T5V6MZi9EhvXvBlC0+aLJ5gQ/NaoblPyQBFeBSFkPExTINNFfxrr1CHNQ0UVeg2bALqPv6p4UBAa2t8oqlCPmaDTN+1dwaUzZhRKDkSf65XyCfvwZ/D6qXU3L9CE8moe+kNcIRM4BJk5LlWLMGwIkQwwW0yHCa/IZ+twqK2Y2iA6VaKFlmWOu5EiKCBHP5dWFGPMD6IrbzRF/mHDZmxMdO6mxCb8ITBEyeVGwgsW3V/SL/GkDrP/CESyteuz/gKLhhqplYZ8ZTqg/76h8JJ0HM5KX0/IJrMTiIHC7z3UJXA4faGRy8tAw1r36P2B+V6GUizf2+u2UcscS6AcjCZnDIPQwRoamfagVbWXB2PcXf+OEI7e7B0PJw8dJTLLWnFRAyIL5n8xam0jC3qlrhI6vo/ieUcE+89LlbPu6BDKSNL/CxDs7pqtLHeE9Y5g+bhBHHwzGO2EMk00=
  on:
    repo: saikatharryc/pm2-prometheus-exporter
